apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-ha-app-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ha
    name: in-cluster
  project: default
  source:
    path: ha/chart-apps
    repoURL: git@github.com:yo0x/devops-smarthome.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - my-val.yaml