apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restreamer-app
  namespace: argocd
spec:
  destination:
    namespace: restreamer
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: restreamer
    repoURL: https://utkuozdemir.org/helm-charts
    targetRevision: 1.1.0
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true