apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-sources-volume-errbot
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    # The address 192.168.99.1 is the Minikube gateway to the host. This way
    # not the container IP will be visible by the NFS server on the host machine,
    # but the IP address of the `minikube ip` command. You will need to
    # grant access to the `minikube ip` IP address.
    server: 192.168.49.1
    path: '/mnt/errbot-data'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sources-volume-claim-errbot
  namespace: default
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: errbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: errbot
  template:
    metadata:
      labels:
        app: errbot
    spec:
      containers:
      - name: errbot
        image: errbotio/errbot:latest
        command: ["pip"]
        args: ["install", "--upgrade pip"]
        command: ["pip"]
        args: ["install", "errbot[slack]"]
        volumeMounts:
          - name: errbot-vol
            mountPath: /home/errbot
      volumes:
        - name: errbot-vol
          persistentVolumeClaim:
            claimName: sources-volume-claim-errbot
---
metadata:
  name: errbot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: errbot

---

apiVersion: v1
kind: Service
metadata:
  name: errbot-srv
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: errbot