apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saas-provider/helm-charts
    targetRevision: 1.0.0
    chart: saas1
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/your-org/meta-repo/main/environments/values-{{.Values.global.env}}.yaml
      values: |
        global:
          env: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: saas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true