# Collect only the static_dhcp facts
- zyxel_vmg8825_facts:
    gather_subset:
      - "!all"
      - "!min"
    gather_network_resources:
      - static_dhcp
      - nat_port_forwards

# Do not collect static_dhcp facts
- zyxel_vmg8825_facts:
    gather_network_resources:
      - "!static_dhcp"

# Collect static_dhcp and minimal default facts
- zyxel_vmg8825_facts:
    gather_subset: min
    gather_network_resources: static_dhcp