apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-octoprint-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: octoprint
    name: in-cluster
  project: default
  source:
    path: 3dprint/apps-of-apps/apps
    repoURL: git@github.com:yo0x/devops-smarthome.git
    targetRevision: HEAD