apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namePrefix: dev-

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: app1-config
  data:
    values-dev.yaml: |
      $(cat ../../environments/values-dev.yaml)