apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu-app
  namespace: argocd
spec:
  destination:
    namespace: mailu
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - my-values.yaml
    chart: mailu
    repoURL: https://mailu.github.io/helm-charts/
    targetRevision: 0.3.5
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true