apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu-app
  namespace: argocd
spec:
  destination:
    namespace: mailu
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
      domain: mail.pentet.co.il
      hostnames:
        - mail.pentet.co.il
      initialAccount:
        domain: mail.pentet.co.il
        password: chang3m3!
        username: mailadmin
      logLevel: INFO
      limits:
        authRatelimit:
          ip: 100/minute;3600/hour
          user: 100/day
        messageSizeLimitInMegabytes: 200
      persistence:
        size: 100Gi
        storageClass: fast
      secretKey: chang3m3!
    chart: mailu
    repoURL: https://mailu.github.io/helm-charts/
    targetRevision: 0.3.5
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true