replicaCount: 1
image:
  repository: askljd23084/fe-yonor
  pullPolicy: Always
  tag: 0.0.2-10
imagePullSecrets:
  - name: regcred
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: yonor.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - yonor.me
      secretName: nginx-tls
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
