image:
  repository: 8gears.container-registry.com/ops/n8n
  tag: 1.81.4
  pullPolicy: Always
imagePullSecrets:
  - name: 8gears-registry-n8n

main:
  config:
    n8n:
      editor_base_url: https://n8n.yonor.me
    executions_mode: queue
    db:
      type: postgresdb
      postgresdb:
        host: 192.168.1.126
        user: postgres
        pool:
          size: 10
        ssl:
          enabled: true
          reject_Unauthorized: true
          ca_file: "/home/ssl/certs/postgresql/ca.crt"
    webhook_url: https://n8n.yonor.me
    queue:
      health:
        check:
          active: true
      bull:
        redis:
          host: n8n-valkey-primary
          port: 6379
  secret:
    n8n:
      encryption_key: "yonor"  # Replace with secure key in production
  extraEnv: &extraEnv
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: db-app
          key: password
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  extraVolumeMounts: &extraVolumeMounts
    - name: db-ca-cert
      mountPath: /home/ssl/certs/postgresql
      readOnly: true
  extraVolumes: &extraVolumes
    - name: db-ca-cert
      secret:
        secretName: db-ca
        items:
          - key: ca.crt
            path: ca.crt
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi

worker:
  enabled: true
  extraEnv: *extraEnv
  extraVolumeMounts: *extraVolumeMounts
  extraVolumes: *extraVolumes

webhook:
  enabled: true
  extraEnv: *extraEnv
  extraVolumeMounts: *extraVolumeMounts
  extraVolumes: *extraVolumes

valkey:
  enabled: true
  architecture: standalone
  sentinel:
    enabled: false
  auth:
    enabled: false
  primary:
    kind: Deployment
    persistence:
      enabled: false
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: n8n.yonor.me
      paths:
        - /
  tls:
    - secretName: ngnix-tls
      hosts:
        - n8n.yonor.me