#Prod like set up with nginx-ingress.  Using local postgres instance instead of CNPG.
image:
  repository: public.ecr.aws/r4n5h0a2/nura/n8n
  tag: latest
# imagePullSecrets:
#   - name: 8gears-registry-n8n

main:
  config:
    db:
      type: postgresdb
      postgresdb:
        host: 192.168.1.126  # Replace with your PostgreSQL host
        user: postgres                            # Replace with your PostgreSQL user
        password: yonor      # Replace with your PostgreSQL password
        pool:
          size: 10
        ssl:
          enabled: false  # Set to true if your local PostgreSQL server uses SSL
          reject_Unauthorized: false #Set to true if you want to reject unauthorized certificates
        #  ca_file: "/path/to/your/ca.crt" #Remove this line if ssl.enabled is false or not needed

  secret:
    n8n:
      encryption_key: "somekey"

  # extraEnv: #This section is removed
  #   DB_POSTGRESDB_PASSWORD:
  #     valueFrom:
  #       secretKeyRef:
  #         name: db-app
  #         key: password
  # Mount the CNPG CA Cert into N8N container #This section is removed
  # extraVolumeMounts:
  #   - name: db-ca-cert
  #     mountPath: /home/ssl/certs/postgresql
  #     readOnly: true
  #
  # extraVolumes: #This section is removed
  #   - name: db-ca-cert
  #     secret:
  #       secretName: db-ca
  #       items:
  #         - key: ca.crt
  #           path: ca.crt
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: n8n-dev.8gears.com
      paths:
        - /
  tls:
    - secretName: n8n-ingress-tls
      hosts:
        - n8n-dev.8gears.com

# cnpg DB cluster request #This section is removed
# extraManifests:
#   - apiVersion: postgresql.cnpg.io/v1
#     kind: Cluster
#     metadata:
#       name: db
#     spec:
#       instances: 1
#       bootstrap:
#         initdb:
#           database: n8n
#           owner: n8n
#       postgresql:
#         parameters:
#           shared_buffers: "64MB"
#       resources:
#         requests:
#           memory: "512Mi"
#         limits:
#           memory: "512Mi"
#       storage:
#         size: 1Gi