apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

commonLabels:
  managed-by: argocd

# Placeholder for generated resources
generatorOptions:
  disableNameSuffixHash: true