apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-reg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.twun.io
    targetRevision: 2.2.3
    chart: twuni/docker-registry 
    helm:
      values: |
        replicaCount: 1
        persistence:
          enabled: true
          size: 30Gi
          deleteEnabled: true
          storageClass: local-storage
          existingClaim: docker-registry-pv-claim-local
        secrets:
          htpasswdSecretName: htpasswd-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-reg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true