apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-reg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://phntom.kix.co.il/charts/
    targetRevision: 1.10.0
    chart: docker-registry
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/environments/docker-reg-vals.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-reg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-docker-reg
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs-client"
  nfs:
    path: /export/k8s-vols
    server: 192.168.1.207
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-docker-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "nfs-client"
  volumeName: pv-docker-reg