apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yonor-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:yo0x/devops-smarthome.git
    path: site/fe
    targetRevision: 1.16.0
    chart: yonor-site
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/environments/fe-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yonor-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
