apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yonor-site-fe
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yo0x/devops-smarthome.git
    path: site/fe
    targetRevision: main
    helm:
      valueFiles:
        - root/environments/fe-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yonor-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
