apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toran-influxdb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.influxdata.com/
    targetRevision: 2.1.2
    chart: influxdb2
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/environments/toran-influxdb-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: toran
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
