# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-ha
#   annotations:
#     "helm.sh/hook": pre-install,pre-upgrade
#     "helm.sh/hook-weight": "-5"
    
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: "nfs-client"
#   nfs:
#     path: /export/k8s-vols
#     server: 192.168.1.207
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-ha
#   namespace: ha-dev
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: "nfs-client"
#   volumeName: pv-ha
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    targetRevision: 0.2.70
    chart: home-assistant
    # namespace: ha-dev
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/environments/ha-values-dev2.yaml

    # plugin:
    #   name: kustomized-helm
    #   env: 
    #     - name: KUSTOMIZE_BASE
    #       value: https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/kustomize/base
    #     - name: KUSTOMIZE_OVERLAY
    #       value: https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/kustomize/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: ha-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # ignoreDifferences:
  # - group: "*"
  #   kind: "*"
  #   jsonPointers:
  #   - /metadata/labels
  # configManagementPlugins:
  #   - name: kustomized-helm
  #     init:
  #       command: ["/bin/sh", "-c"]
  #       args: ["helm dependency build"]
  #     generate:
  #       command: ["/bin/sh", "-c"]
  #       args: ["helm template --release-name release-name . > all.yaml && kustomize build"]