apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://geek-cookbook.github.io/charts
    targetRevision: 13.5.0
    chart: home-assistant
    namespace: ha-dev
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/environments/ha-values-dev.yaml

    # plugin:
    #   name: kustomized-helm
    #   env: 
    #     - name: KUSTOMIZE_BASE
    #       value: https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/kustomize/base
    #     - name: KUSTOMIZE_OVERLAY
    #       value: https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/kustomize/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: ha-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # ignoreDifferences:
  # - group: "*"
  #   kind: "*"
  #   jsonPointers:
  #   - /metadata/labels
  # configManagementPlugins:
  #   - name: kustomized-helm
  #     init:
  #       command: ["/bin/sh", "-c"]
  #       args: ["helm dependency build"]
  #     generate:
  #       command: ["/bin/sh", "-c"]
  #       args: ["helm template --release-name release-name . > all.yaml && kustomize build"]