# svc-ha-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ha-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8123
      protocol: TCP
  clusterIP: None  # Headless to use custom endpoints

---
# endpoints-ha-service.yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: ha-service
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.239
    ports:
      - port: 8123

---
# ingress-ha-service.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-service-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: ha.yonor.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ha-service
                port:
                  number: 80
  tls:
    - hosts:
        - ha.yonor.me
      secretName: ha-service-tls
