# svc-c-domain.yaml
apiVersion: v1
kind: Service
metadata:
  name: ha-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  clusterIP: None  # Headless service to allow custom endpoints
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ha-service
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.126
    ports:
      - port: 8123
---
# ingress-c-domain.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c-domain-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: ha.yonor.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ha-service
                port:
                  number: 8123
