apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BerriAI/litellm.git
    path: deploy/charts/litellm-helm
    targetRevision: main
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/environments/litellm-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: litellm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
