apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd # Or your preferred ArgoCD application namespace
spec:
  project: default # Or your specific ArgoCD project

  source:
    # repoURL should point to the full OCI path of the chart.
    repoURL: oci://8gears.container-registry.com/library/n8n
    # 'chart' specifies the name of the Helm chart.
    chart: n8n
    # 'targetRevision' is the specific version of the Helm chart to deploy.
    # Updated based on the successful helm install command.
    targetRevision: 0.1.1
    # 'path' is generally not used for OCI Helm chart sources and should be removed or left empty.

    helm:
      # valueFiles remains the same, pointing to your custom values.
      valueFiles:
        - https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/environments/n8n-values.yaml
      # You can also include inline values here if needed:
      # values: |
      #   key: value
      #   anotherKey:
      #     nested: value

  destination:
    server: https://kubernetes.default.svc # Target Kubernetes cluster
    namespace: n8n # Target namespace for n8n deployment

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # Optional: Add syncOptions if needed
    # syncOptions:
    #   - CreateNamespace=true # Example: Ensures the namespace exists
