apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.openwebui.com/
    targetRevision: 3.3.2
    chart: open-webui
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/environments/open-webui-values.yaml
    parameters:
      - name: image.tag
        value: latest

  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
