apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha-server-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/home/y7x/K8S_LOCAL/ha"