apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-server-pv-claim
  namespace: ha-dev
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi