apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vscode
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coder/code-server.git
    targetRevision: main
    path: ci/helm-chart
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/yo0x/devops-smarthome/main/root/environments/vscode-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vscode
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
