apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ha-app
  namespace: argocd
spec:
  destination:
    namespace: ha
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://geek-cookbook.github.io/charts
    targetRevision: 13.5.0
    chart: home-assistant
    helm:
      values: |
        service:
          main:
            ports:
              http:
                port: 8123
        hostNetwork: true
        TZ: 'Asia/Jerusalem'
        dnsPolicy: ClusterFirstWithHostNet
        addons:
        # -- Enable and configure codeserver for the chart.
        #    This allows for easy access to configuration.yaml
        # @default -- See values.yaml
        codeserver:
          enabled: true
          args:
            - --auth
            - none
            - --user-data-dir
            - /data/config/.vscode
          volumeMounts:
          - name: config
            mountPath: /data/config


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
