apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ha-app
  namespace: argocd
spec:
  destination:
    namespace: ha
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: home-assistant
    repoURL: https://geek-cookbook.github.io/charts
    targetRevision: 13.5.0
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true