apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ha-app
  namespace: argocd
spec:
  destination:
    namespace: ha
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://k8s-home-lab.github.io/helm-charts'
    targetRevision: 14.0.1
    chart: home-assistant
    helm:
      values: |
        service:
          main:
            ports:
              http:
                port: 8124
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
