apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:yo0x/devops-smarthome.git
    targetRevision: HEAD
    path: monitoring
    helm: {}
      # valueFiles:
      # - values-prometheus.yaml
      # - values-grafana.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
  server: 192.168.1.101
  path: /mnt/DATA/k8s/monitoring
mountOptions:
  - soft
  - intr
  - nolock
  - rw