apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:yo0x/devops-smarthome.git
    targetRevision: HEAD
    path: monitoring
    helm: {}
      # valueFiles:
      # - values-prometheus.yaml
      # - values-grafana.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
