prometheus:
  global:
    evaluation_interval: 1m
    scrape_interval: 1m
    scrape_timeout: 10s

  server:
    persistentVolume:
      enabled: true
      storageClass: ""
      size: 8Gi
      accessModes:
        - ReadWriteOnce
      existingClaim: prometheus-server-pv-claim

  alertmanager:
    persistentVolume:
      enabled: true
      storageClass: ""
      size: 2Gi
      accessModes:
        - ReadWriteOnce
      existingClaim: prometheus-server-alertmanager-pv

grafana:
  persistence:
    enabled: true
    storageClassName: ""
    size: 5Gi
    accessModes:
      - ReadWriteOnce
    existingClaim: grafana-server-pv-claim

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true