apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saas-provider/helm-charts
    targetRevision: 1.0.0
    chart: saas1
  destination:
    server: https://kubernetes.default.svc
    namespace: saas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true