spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:yo0x/devops-smarthome.git
    targetRevision: HEAD

domain: mail.pentet.co.il
hostnames:
  - mail.pentet.co.il
initialAccount:
  domain: mail.pentet.co.il
  password: chang3m3!
  username: mailadmin
logLevel: INFO
limits:
  authRatelimit:
    ip: 100/minute;3600/hour
    user: 100/day
  messageSizeLimitInMegabytes: 200
persistence:
  size: 100Gi
  storageClass: fast
secretKey: chang3m3!