apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octoprint-app
  namespace: argocd
spec:
  destination:
    namespace: octoprint
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 3dprint/apps-of-apps/delta
    repoURL: git@github.com:yo0x/devops-smarthome.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true