---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: docker-registry-ingressroute
  namespace: docker-reg

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`yonor.me`) && PathPrefix(`/docker-registry`)
      kind: Rule
      services:
        - name: docker-registry
          port: 5000
