apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yo0x/devops-smarthome.git
    targetRevision: HEAD
    path: root/argo-cd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: ha-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: # ignore differences in the following fields Docker Registry
    - group: argoproj.io
      kind: Application
      name: docker-reg
      namespace: argocd
      jsonPointers:
      - /spec/source/path