---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octoprint-app
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: build.enabled
          value: "false"
        - name: deploy.route.enabled
          value: "false"
        - name: image.name
          value: octoprint/octoprint
    chart: geek-cookbook/octoprint
    repoURL: https://geek-cookbook.github.io/charts/
    targetRevision: 6.4.2
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true