apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octoprint-app
  namespace: argocd
spec:
  destination:
    namespace: octoprint
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: build.enabled
          value: "false"
        - name: deploy.route.enabled
          value: "false"
        - name: image.name
          value: octoprint/octoprint
        - name: image.tag
          value: latest
        - name: livenessProbe.enabled
          value: "false"
        - name: readinessProbe.enabled
          value: "false"
        - name: nodeSelector.dedicated
          value: 3dprinter
        - name: tolerations
          value: |
            - key: "dedicated"
              operator: "Equal"
              value: "3dprinter"
              effect: "NoSchedule"
    chart: octoprint
    repoURL: https://halkeye.github.io/helm-charts/
    targetRevision: 0.1.1
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true