apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octoprint-app
  namespace: argocd
spec:
  destination:
    namespace: octoprint
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: octoprint
    repoURL: https://halkeye.github.io/helm-charts/
    targetRevision: 0.1.1
    helm:
      valueFiles:
        - ../values.yaml
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true