apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
   worker_processes  1;
    
    events {
        worker_connections  1024;
    }
    
    http {
        include            mime.types;
        default_type       application/octet-stream;
        sendfile           on;
        keepalive_timeout  65;

        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }
  
        upstream "octoprint" {
            server octoprint-app:5000;
        }
    
        upstream "mjpg-streamer" {
            server restreamer-app:80;
        }
    
        server {
            listen       80;
            server_name  localhost;
            
            location /del {
                proxy_pass http://octoprint-app/;
                proxy_set_header Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Scheme $scheme;
                proxy_http_version 1.1;

                client_max_body_size 0;    
            }

            location /webcam/ {
                proxy_pass http://restreamer-app/;
            }

            # redirect server error pages to the static page /50x.html
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
        }
    }