apiVersion: v1
kind: PersistentVolume
metadata:
  name: octo-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /home/y7x/k8s-sc/ha
    server: 192.168.1.126
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octo-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: octo-pv