apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influxdb
  namespace: toran
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs-client"
  nfs:
    path: /export/k8s-vols
    server: 192.168.1.207
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octo-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: octo-pv