apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv-local
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  hostPath:
    path: "/home/y7x/K8S_LOCAL/docker-reg"