apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../apps/app1

commonLabels:
  app: app1

configMapGenerator:
- name: app1-config
  files:
  - ../../environments/values-dev.yaml