build:
  enabled: false
deploy:
  route:
    enabled: false
image:
  name: octoprint/octoprint
  tag: latest
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
nodeSelector:
  type: raspberrypi