spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:yo0x/devops-smarthome.git
    targetRevision: HEAD

build:
  enabled: false
deploy:
  route:
    enabled: false
image:
  repository: octoprint/octoprint
  tag: 1.9.3
  pullPolicy: Always
livenessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
nodeSelector:
  type: hme43
service:
  type: NodePort
  port: 5000
  nodePort: 30000